### ISSUE TITLE
Research on greenfoot and protoype

### ISSUE THREAD

**Issue by gauravchodwadia** [CMPE202-TEAM03-SPRING16/GameWithDesignPattern#3]
Based on research by Gaurav, an option to chose the game development environment is GreenFoot. Aneri will dig deep and come up with pros and cons of using GreenFoot.

**Comment by Aneri20** [comment]
http://www.greenfoot.org/overview

I researched on pros and cons of using greenfoot game engine.The interface is simple and easy to build.The actors are programmed in standard textual Java code, providing a combination of programming experience in a traditional text-based language with visual execution.Also,since we have used greenfoot in the labs and greenfoot I recommend using greenfoot as our engine
